# Generated by Django 4.1.4 on 2023-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('regform', '0002_user_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='from@example.com', max_length=75),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Ivanov', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Ivan', max_length=200),
        ),
    ]
